medikago/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('user/', include('user.urls'))
]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path('', views.index, name="home"),
    path('dashboard/admin/', views.dashboardAdmin, name="dashAdmin"),
    path('dashboard/admin/profil', views.profil, name="profil"),
    ## konsultasi ##
    path('dashboard/admin/buatSesiKonsultasi',
         views.buatKonsultasi, name="buatKonsultasi"),
    path('dashboard/admin/daftarSesiKonsultasi',
         views.daftarKonsultasi, name="daftarKonsultasi"),
    path('dashboard/admin/updateSesiKonsultasi/<str:id_konsultasi>/',
         views.updateKonsultasi, name="updateKonsultasi"),
    path('dashboard/admin/deleteSesiKonsultasi/<str:id_konsultasi>',
         views.deleteKonsultasi, name="deleteKonsultasi"),
    ## poliklinik ##
    path('dashboard/admin/buatLayananJadwalPoliklinik',
         views.buatLayananJadwalPoliklinik, name="buatLayananJadwalPoliklinik"),
    path('dashboard/admin/daftarLayananJadwalPoliklinik',
         views.daftarLayananJadwalPoliklinik, name="daftarLayananJadwalPoliklinik"),
    path('dashboard/admin/updateLayananJadwalPoliklinik/<str:id_poliklinik>',
         views.updateLayananJadwalPoliklinik, name="updateLayananJadwalPoliklinik"),
    path('dashboard/admin/deleteLayananJadwalPoliklinik/<str:id_poliklinik>',
         views.deleteLayananJadwalPoliklinik, name="deleteLayananJadwalPoliklinik"),
    ## rs ##
    path('dashboard/admin/buatRsCabang',
         views.buatRsCabang, name="buatRsCabang"),
    path('dashboard/admin/daftarRsCabang',
         views.daftarRsCabang, name="daftarRsCabang"),
    path('dashboard/admin/updateRsCabang/<str:kode_rs>',
         views.updateRsCabang, name="updateRsCabang"),
    path('dashboard/admin/deleteRsCabang/<str:kode_rs>',
         views.deleteRsCabang, name="deleteRsCabang"),
    path('dashboard/admin/daftarDokterRSCabang',
         views.daftarDokterRsCabang, name="daftarDokterRSCabang"),
    path('dashboard/admin/listDokterRSCabang',
         views.listDokterRsCabang, name="listDokterRSCabang"),
    path('dashboard/admin/updateDokterRSCabang/<str:id_dokter>/<str:kode_rs>',
         views.updateDokterRsCabang, name="updateDokterRSCabang"),
    path('dashboard/admin/deleteDokterRSCabang/<str:id_dokter>/<str:kode_rs>',
         views.deleteDokterRsCabang, name="deleteDokterRSCabang"),

    ## tindakan ##
    path('dashboard/admin/buatTindakan',
         views.buatTindakan, name='buatTindakan'),
    path('dashboard/admin/daftarTindakan',
         views.daftarTindakan, name='daftarTindakan'),
    path('dashboard/admin/updateTindakan/<str:no_urut>/<str:id_konsultasi>',
         views.updateTindakan, name="updateTindakan"),
    path('dashboard/admin/deleteTindakan/<str:no_urut>/<str:id_konsultasi>',
         views.deleteTindakan, name="deleteTindakan"),
    path('dashboard/admin/buatTindakanPoliklinik',
         views.buatTindakanPoliklinik, name='buatTindakanPoliklinik'),
    path('dashboard/admin/daftarTindakanPoliklinik',
         views.daftarTindakanPoliklinik, name='daftarTindakanPoliklinik'),
    path('dashboard/admin/updateTindakanPoliklinik/<str:id_tindakan_poli>',
         views.updateTindakanPoliklinik, name="updateTindakanPoliklinik"),
    path('dashboard/admin/deleteTindakanPoliklinik/<str:id_tindakan_poli>',
         views.deleteTindakanPoliklinik, name="deleteTindakanPoliklinik"),
    ## transaksi ##
    path('dashboard/admin/buatTransaksi',
         views.buatTransaksi, name="buatTransaksi"),
    path('dashboard/admin/daftarTransaksi',
         views.daftarTransaksi, name="daftarTransaksi"),
    path('dashboard/admin/updateTransaksi/<str:id_transaksi>',
         views.updateTransaksi, name="updateTransaksi"),
    path('dashboard/admin/deleteTransaksi/<str:id_transaksi>',
         views.deleteTransaksi, name="deleteTransaksi"),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('roles/', views.roles, name="roles"),
    path('registerAdmin/', views.registerAdmin, name="registerAdmin"),
    path('registerDokter/', views.registerDokter, name="registerDokter"),
    path('registerPasien/', views.registerPasien, name="registerPasien"),
]

pages/templates/dashboardAdmin/Tindakan/buatTindakan.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='tindakan' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block custom_styles %}
<style>
    [data-role="dynamic-fields"]>.form-inline+.form-inline {
        margin-top: 0.5em;
    }

    [data-role="dynamic-fields"]>.form-inline [data-role="add"] {
        display: none;
    }

    [data-role="dynamic-fields"]>.form-inline:last-child [data-role="add"] {
        display: inline-block;
    }

    [data-role="dynamic-fields"]>.form-inline:last-child [data-role="remove"] {
        display: none;
    }
</style>
{% endblock custom_styles %}

{% block content %}

<div class="d-flex justify-content-center flex-column" style="width: 30vw;">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatTindakan' %}">Tindakan</a></li>
        <li class="breadcrumb-item active">Buat Tindakan</li>
    </ol>
    <div class="jumbotron">
        <h2 class="">Form Pembuatan Tindakan</h2>
        <form action="{% url 'pages:buatTindakan' %}" method = "POST">
            {% csrf_token %}
            <div class="form-group">
                <div class="form-group">
                    <label for="inputIdKonsultasi">ID Konsultasi</label>
                    <select name="id_konsultasi" class="form-control" id="inputIdKonsultasi" required>
                        {% for k in id_konsultasi %}
                        <option>{{ k.id_konsultasi }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="inputIdTransaksi">ID Transaksi</label>
                    <select name="id_transaksi" class="form-control" id="inputIdTransaksi" required>
                        {% for t in id_transaksi %}
                        <option>{{ t.id_transaksi }}</option>
                        {% endfor %}
                    </select>
                </div>
                <label for="inputCatatan">Catatan</label>
                <input name = "catatan" type="text" class="form-control" id="inputCatatan" required>
                <label for="inputIdTindakanPoli">Daftar ID Tindakan Poliklinik</label>
                <div data-role="dynamic-fields">
                    <div class="form-inline">
                        <div class="form-group">
                            <select name ="id_tindakan_poli" class="form-control" id="inputIdTindakanPoli" required>
                                {% for tp in id_tindakan_poli %}
                                <option>{{ tp.id_tindakan_poli }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <button class="btn btn-danger ml-2" data-role="remove">
                            <span class="glyphicon glyphicon-remove">-</span>
                        </button>
                        <button class="btn btn-primary ml-2" data-role="add">
                            <span class="glyphicon glyphicon-plus">+</span>
                        </button>
                    </div> <!-- /div.form-inline -->
                </div>
            </div>
            <p class="lead mt-5">
                <button class="btn btn-primary btn-lg mt-3" href="#" role="button">Submit</button>
            </p>
        </form>
    </div>
</div>
{% endblock content %}
{% block custom_scripts %}
<script>
    $(function () {
        // Remove button click
        $(document).on(
            'click',
            '[data-role="dynamic-fields"] > .form-inline [data-role="remove"]',
            function (e) {
                e.preventDefault();
                $(this).closest('.form-inline').remove();
            }
        );
        // Add button click
        $(document).on(
            'click',
            '[data-role="dynamic-fields"] > .form-inline [data-role="add"]',
            function (e) {
                e.preventDefault();
                var container = $(this).closest('[data-role="dynamic-fields"]');
                new_field_group = container.children().filter('.form-inline:first-child').clone();
                new_field_group.find('input').each(function () {
                    $(this).val('');
                });
                container.append(new_field_group);
            }
        );
    });
</script>
{% endblock custom_scripts %}

pages/templates/dashboardAdmin/Tindakan/buatTindakanPoliklinik.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='tindakan' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}

<div class="d-flex justify-content-center flex-column" style="width: 30vw;">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatTindakanPoliklinik' %}">Tindakan</a></li>
        <li class="breadcrumb-item active">Buat Tindakan Poliklinik</li>
    </ol>
    <div class="jumbotron">
        <h2 class="">Form Pembuatan Tindakan Poliklinik</h2>
        <form action = "{% url 'pages:buatTindakanPoliklinik' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <div class="form-group">
                    <label for="InputIdPoliklinik">ID Poliklinik</label>
                    <select class="form-control" id="inputIdPoliklinik" name = "id_poliklinik" required>
                        {% for p in id_poliklinik %}
                        <option>{{ p.id_poliklinik }}</option>
                        {% endfor %}
                    </select>
                </div>
                <label for="inputNamaTindakan">Nama Tindakan</label>
                <input name = "nama_tindakan" type="text" class="form-control" id="inputNamaTindakan" required>

                <label for="inputDeskripsi">Deskripsi</label>
                <input type="text" class="form-control" id="inputDeskripsi" name = "deskripsi" required>

                <label for="inputTarif">Tarif</label>
                <input type="text" class="form-control" id="inputTarif" name ="tarif" required>

            </div>
            <p class="lead mt-5">
                <button class="btn btn-primary btn-lg mt-3" href="#" role="button">Submit</button>
            </p>
        </form>
    </div>
</div>
{% endblock content %}

pages/templates/dashboardAdmin/Tindakan/daftarTindakan.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='tindakan' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}

<div class="d-flex justify-content-center flex-column">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatTindakan' %}">Tindakan Poliklinik</a></li>
        <li class="breadcrumb-item active">Daftar Tindakan</li>
    </ol>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">ID Konsultasi</th>
            <th scope="col">Nomor Urut</th>
            <th scope="col">Biaya</th>
            <th scope="col">Catatan</th>
            <th scope="col">ID Transaksi</th>
            {% if request.session.user.role == "admin" %}
            <th scope="col">Action</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
            {% for t in tindakan %}
            <tr>
                    <th scope="row">{{ t.id_konsultasi }}</th>
                    <td>{{ t.no_urut }}</td>
                    <td>{{ t.biaya }}</td>
                    <td>{{ t.catatan }}</td>
                    <td>{{ t.id_transaksi }}</td>
                {% if request.session.user.role == "admin" %}

                <td class="d-flex">
                    <a class="btn btn-primary" href="{% url 'pages:updateTindakan' t.no_urut t.id_konsultasi %}">Update</a>
                        <form action ="{% url 'pages:deleteTindakan' t.no_urut t.id_konsultasi %}" method = "POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger" style="color: #fff;">Delete</button>
                </form>
                </td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <!-- update Modal -->
    <div class="modal fade" id="update-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Form Update Tindakan</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="hide" id="success">
                        <div class="container d-flex justify-content-center align-items-center">
                            <lottie-player src="https://assets3.lottiefiles.com/packages/lf20_3w07tT.json"
                                           background="transparent" speed="1" style="width: 200px; height: 200px;" loop autoplay>
                            </lottie-player>
                        </div>
                    </div>
                    <form id="modal-form" class="">
                        <div class="form-group">
                            <fieldset disabled="">
                                <label class="control-label" for="disabledInput">ID Konsultasi</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="1" disabled="">
                            </fieldset>
                        </div>
                        <div class="form-group">
                            <fieldset disabled="">
                                <label class="control-label" for="disabledInput">Nomer Urut</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="1" disabled="">
                            </fieldset>
                        </div>
                        <div class="form-group">
                            <fieldset disabled="">
                                <label class="control-label" for="disabledInput">Biaya</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="Rp 0"
                                       disabled="">
                            </fieldset>
                        </div>
                        <div class="form-group">
                            <label class="col-form-label" for="inputDefault">Catatan</label>
                            <input type="text" class="form-control" value="Selesai" placeholder="Default input"
                                   id="inputDefault">
                        </div>
                        <div class="form-group">
                            <fieldset disabled="">
                                <label class="control-label" for="disabledInput">ID Transaksi</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="1" disabled="">
                            </fieldset>
                        </div>
                    </form>
                </div>
                <div class="modal-footer d-flex justify-content-center align-items-center">
                    <button type="button" class="btn btn-primary" onclick="update()">Update</button>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}
{% block custom_scripts %}
<script>
    function update() {
        console.log("update Succes")
        $('#modal-form').toggleClass('hide');
        $('#success').toggleClass('hide');
        setTimeout(function () {
            $('#modal-form').toggleClass('hide');
            $('#success').toggleClass('hide');
        }, 3000);
    }
</script>
{% endblock custom_scripts %}

pages/templates/dashboardAdmin/Tindakan/daftarTindakanPoliklinik.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='tindakan' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}

<div class="d-flex justify-content-center flex-column">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatTindakanPoliklinik' %}">Tindakan Poliklinik</a></li>
        <li class="breadcrumb-item active">Daftar Tindakan Poliklinik</li>
    </ol>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">ID Tindakan Poliklinik</th>
            <th scope="col">ID Poliklinik</th>
            <th scope="col">Nama Tindakan</th>
            <th scope="col">Tarif</th>
            <th scope="col">Deskripsi</th>
            {% if request.session.user.role == "admin" %}
            <th scope="col">Action</th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {% for tp in tindakan_poli %}
        <tr>
            <th scope="row">{{ tp.id_tindakan_poli }}</th>
            <td>{{ tp.id_poliklinik }}</td>
            <td>{{ tp.nama_tindakan }}</td>
            <td>{{tp.tarif}}</td>
            <td>{{tp.deskripsi}}</td>
            {% if request.session.user.role == "admin" %}
            <td class="d-flex">
                <a class="btn btn-primary" href="{% url 'pages:updateTindakanPoliklinik' tp.id_tindakan_poli %}">Update</a>
                <form action ="{% url 'pages:deleteTindakanPoliklinik' tp.id_tindakan_poli %}" method = "POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" style="color: #fff;">Delete</button>
                </form>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <!-- update Modal -->
    <div class="modal fade" id="update-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Form Update Tindakan</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="hide" id="success">
                        <div class="container d-flex justify-content-center align-items-center">
                            <lottie-player src="https://assets3.lottiefiles.com/packages/lf20_3w07tT.json"
                                           background="transparent" speed="1" style="width: 200px; height: 200px;" loop autoplay>
                            </lottie-player>
                        </div>
                    </div>
                    <form id="modal-form" class="">
                        <div class="form-group">
                            <fieldset disabled="">
                                <label class="control-label" for="disabledInput">ID Tindakan Poliklinik</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="1" disabled="">
                            </fieldset>
                        </div>
                        <div class="form-group">
                            <fieldset disabled="">
                                <label class="control-label" for="disabledInput">ID Poliklinik</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="1" disabled="">
                            </fieldset>
                        </div>
                        <div class="form-group">
                            <fieldset disabled="">
                                <label class="control-label" for="disabledInput">Nama Tindakan</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="Observasi" disabled="">
                            </fieldset>
                        </div>
                        <div class="form-group">
                            <fieldset disabled="">
                                <label class="control-label" for="disabledInput">Tarif</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="Rp 0"
                                       disabled="">
                            </fieldset>
                        </div>
                        <div class="form-group">
                            <label class="col-form-label" for="inputDefault">Deskripsi</label>
                            <input type="text" class="form-control" value="Melakukan Observasi" placeholder="Default input"
                                   id="inputDefault">
                        </div>
                    </form>
                </div>
                <div class="modal-footer d-flex justify-content-center align-items-center">
                    <button type="button" class="btn btn-primary" onclick="update()">Update</button>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}
{% block custom_scripts %}
<script>
    function update() {
        console.log("update Succes")
        $('#modal-form').toggleClass('hide');
        $('#success').toggleClass('hide');
        setTimeout(function () {
            $('#modal-form').toggleClass('hide');
            $('#success').toggleClass('hide');
        }, 3000);
    }
</script>
{% endblock custom_scripts %}

pages/templates/dashboardAdmin/Tindakan/updateTindakan.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='konsultasi' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}
<div class="d-flex justify-content-center flex-column" style="width: 30vw;">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatTindakan' %}">Tindakan</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:daftarTindakan' %}">Daftar Tindakan</a></li>
        <li class="breadcrumb-item active">Update Tindakan</li>
    </ol>
    <div class="jumbotron" style="padding: 3rem 2rem;">
        <h2 class="">Update Tindakan</h2>
        <form action="{% url 'pages:updateTindakan' no_urut id_konsultasi %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputKodeRs">ID Konsultasi</label>
                <input type="text" class="form-control" id="inputKodeRs" name="id_konsultasi" readonly
                       value="{{ id_konsultasi }}">
            </div>
            <div class="form-group">
                <label for="inputNama">No Urut</label>
                <input type="text" class="form-control" id="inputNama" name="no_urut" readonly
                       value="{{ no_urut }}">
            </div>
            <div class="form-group">
                <label for="inputTanggal">Biaya</label>
                <input type="number" class="form-control" id="inputTanggal" name="biaya" readonly value="{{ biaya }}" >
            </div>
            <div class="form-group">
                <label for="inputJalan">Catatan</label>
                <input type="text" class="form-control" id="inputJalan" name="catatan"  value="{{ catatan }}">
            </div>
            <div class="form-group">
                <label for="inputNomor">ID Transaksi</label>
                <input type="text" class="form-control" id="inputNomor" name="id_transaksi" readonly value="{{ id_transaksi }}">
            </div>
            <div class="form-group">
                <label for="inputKota">Daftar ID Tindakan Poli</label>
                <input type="text" class="form-control" id="inputKota" name="id_tindakan_poli" readonly
                       value="{{ id_tindakan_poli }}">
            </div>
            <button class="btn btn-primary btn-lg mt-3" href="#" role="button">Submit</button>
        </form>
    </div>
</div>

{% endblock content %}

pages/templates/dashboardAdmin/Tindakan/updateTindakanPoliklinik.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='konsultasi' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}
<div class="d-flex justify-content-center flex-column" style="width: 30vw;">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatTindakanPoliklinik' %}">Tindakan Poliklinik</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:daftarTindakanPoliklinik' %}">Daftar Tindakan Poliklinik</a></li>
        <li class="breadcrumb-item active">Update Tindakan</li>
    </ol>
    <div class="jumbotron" style="padding: 3rem 2rem;">
        <h2 class="">Update Tindakan Poliklinnik</h2>
        <form action="{% url 'pages:updateTindakanPoliklinik' id_tindakan_poli %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputKodeRs">ID Tindakan Poliklinik</label>
                <input type="text" class="form-control" id="inputKodeRs" name="id_tindakan_poli" readonly
                       value="{{ id_tindakan_poli }}">
            </div>
            <div class="form-group">
                <label for="inputNama">ID Poliklinik</label>
                <input type="text" class="form-control" id="inputNama" name="id_poliklinik" readonly
                       value="{{ id_poliklinik }}">
            </div>
            <div class="form-group">
                <label for="inputTanggal">Nama Tindakan</label>
                <input type="text" class="form-control" id="inputTanggal" name="nama_tindakan" value="{{ nama_tindakan }}" >
            </div>
            <div class="form-group">
                <label for="inputJalan">Deskripsi</label>
                <input type="text" class="form-control" id="inputJalan" name="deskripsi"  value="{{ deskripsi }}">
            </div>
            <div class="form-group">
                <label for="inputNomor">Tarif</label>
                <input type="number" class="form-control" id="inputNomor" name="tarif"  value="{{ tarif }}">
            </div>

            <button class="btn btn-primary btn-lg mt-3" href="#" role="button">Submit</button>
        </form>
    </div>
</div>

{% endblock content %}