medikago/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('user/', include('user.urls'))
]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path('', views.index, name="home"),
    path('dashboard/admin/', views.dashboardAdmin, name="dashAdmin"),
    path('dashboard/admin/profil', views.profil, name="profil"),
    ## konsultasi ##
    path('dashboard/admin/buatSesiKonsultasi',
         views.buatKonsultasi, name="buatKonsultasi"),
    path('dashboard/admin/daftarSesiKonsultasi',
         views.daftarKonsultasi, name="daftarKonsultasi"),
    path('dashboard/admin/updateSesiKonsultasi/<str:id_konsultasi>/',
         views.updateKonsultasi, name="updateKonsultasi"),
    path('dashboard/admin/deleteSesiKonsultasi/<str:id_konsultasi>',
         views.deleteKonsultasi, name="deleteKonsultasi"),
    ## poliklinik ##
    path('dashboard/admin/buatLayananJadwalPoliklinik',
         views.buatLayananJadwalPoliklinik, name="buatLayananJadwalPoliklinik"),
    path('dashboard/admin/daftarLayananJadwalPoliklinik',
         views.daftarLayananJadwalPoliklinik, name="daftarLayananJadwalPoliklinik"),
    path('dashboard/admin/updateLayananJadwalPoliklinik/<str:id_poliklinik>',
         views.updateLayananJadwalPoliklinik, name="updateLayananJadwalPoliklinik"),
    path('dashboard/admin/deleteLayananJadwalPoliklinik/<str:id_poliklinik>',
         views.deleteLayananJadwalPoliklinik, name="deleteLayananJadwalPoliklinik"),
    ## rs ##
    path('dashboard/admin/buatRsCabang',
         views.buatRsCabang, name="buatRsCabang"),
    path('dashboard/admin/daftarRsCabang',
         views.daftarRsCabang, name="daftarRsCabang"),
    path('dashboard/admin/updateRsCabang/<str:kode_rs>',
         views.updateRsCabang, name="updateRsCabang"),
    path('dashboard/admin/deleteRsCabang/<str:kode_rs>',
         views.deleteRsCabang, name="deleteRsCabang"),
    path('dashboard/admin/daftarDokterRSCabang',
         views.daftarDokterRsCabang, name="daftarDokterRSCabang"),
    path('dashboard/admin/listDokterRSCabang',
         views.listDokterRsCabang, name="listDokterRSCabang"),
    path('dashboard/admin/updateDokterRSCabang/<str:id_dokter>/<str:kode_rs>',
         views.updateDokterRsCabang, name="updateDokterRSCabang"),
    path('dashboard/admin/deleteDokterRSCabang/<str:id_dokter>/<str:kode_rs>',
         views.deleteDokterRsCabang, name="deleteDokterRSCabang"),

    ## tindakan ##
    path('dashboard/admin/buatTindakan',
         views.buatTindakan, name='buatTindakan'),
    path('dashboard/admin/daftarTindakan',
         views.daftarTindakan, name='daftarTindakan'),
    path('dashboard/admin/updateTindakan/<str:no_urut>/<str:id_konsultasi>',
         views.updateTindakan, name="updateTindakan"),
    path('dashboard/admin/deleteTindakan/<str:no_urut>/<str:id_konsultasi>',
         views.deleteTindakan, name="deleteTindakan"),
    path('dashboard/admin/buatTindakanPoliklinik',
         views.buatTindakanPoliklinik, name='buatTindakanPoliklinik'),
    path('dashboard/admin/daftarTindakanPoliklinik',
         views.daftarTindakanPoliklinik, name='daftarTindakanPoliklinik'),
    path('dashboard/admin/updateTindakanPoliklinik/<str:id_tindakan_poli>',
         views.updateTindakanPoliklinik, name="updateTindakanPoliklinik"),
    path('dashboard/admin/deleteTindakanPoliklinik/<str:id_tindakan_poli>',
         views.deleteTindakanPoliklinik, name="deleteTindakanPoliklinik"),
    ## transaksi ##
    path('dashboard/admin/buatTransaksi',
         views.buatTransaksi, name="buatTransaksi"),
    path('dashboard/admin/daftarTransaksi',
         views.daftarTransaksi, name="daftarTransaksi"),
    path('dashboard/admin/updateTransaksi/<str:id_transaksi>',
         views.updateTransaksi, name="updateTransaksi"),
    path('dashboard/admin/deleteTransaksi/<str:id_transaksi>',
         views.deleteTransaksi, name="deleteTransaksi"),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('roles/', views.roles, name="roles"),
    path('registerAdmin/', views.registerAdmin, name="registerAdmin"),
    path('registerDokter/', views.registerDokter, name="registerDokter"),
    path('registerPasien/', views.registerPasien, name="registerPasien"),
]

pages/templates/dashboardAdmin/RSCabang/buatRsCabang.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='RS' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}
<div class="d-flex justify-content-center flex-column" style="width: 30vw;">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatRsCabang' %}">RS Cabang</a></li>
        <li class="breadcrumb-item active">Buat RS</li>
    </ol>
    <div class="jumbotron" style="padding: 3rem 2rem;">
        <h2 class="">Buat RS Cabang</h2>
        <form action="{% url 'pages:buatRsCabang' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputKodeRs">Kode RS Cabang</label>
                <input type="text" class="form-control" id="inputKodeRs" name="kode_rs" required>
            </div>
            <div class="form-group">
                <label for="inputNama">Nama</label>
                <input type="text" class="form-control" id="inputNama" name="nama" required>
            </div>
            <div class="form-group">
                <label for="inputTanggal">Tanggal Pendirian</label>
                <input type="date" class="form-control" id="inputTanggal" name="tanggal_pendirian" required>
            </div>
            <div class="form-group">
                <label for="inputJalan">Jalan</label>
                <input type="text" class="form-control" id="inputJalan" name="jalan">
            </div>
            <div class="form-group">
                <label for="inputNomor">Nomor</label>
                <input type="number" class="form-control" id="inputNomor" name="nomor">
            </div>
            <div class="form-group">
                <label for="inputKota">Kota</label>
                <input type="text" class="form-control" id="inputKota" name="kota" required>
            </div>
            <button class="btn btn-primary btn-lg mt-3" href="#" role="button">Submit</button>
        </form>
    </div>
</div>

{% endblock content %}

pages/templates/dashboardAdmin/RSCabang/daftarDokterRSCabang.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='RS' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}
<div class="d-flex justify-content-center flex-column" style="width: 30vw;">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatRsCabang' %}">RS Cabang</a></li>
        <li class="breadcrumb-item active">Daftarkan Dokter RS Cabang</li>
    </ol>
    <div class="jumbotron" style="padding: 3rem 2rem;">
        <h2 class="">Daftarkan Dokter RS Cabang</h2>
        <form action="{% url 'pages:daftarDokterRSCabang' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <div class="form-group">
                    <label for="inputIdDokter">ID Dokter</label>
                    <select name="id_dokter" class="form-control" id="inputIdDokter">
                        {% for k in id_dokter %}
                        <option>{{ k.id_dokter }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group">
                    <label for="inputKodeRs">Kode RS</label>
                    <select name="kode_rs" class="form-control" id="inputKodeRs">
                        {% for t in kode_rs %}
                        <option>{{ t.kode_rs }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <p class="lead mt-5">
                <button class="btn btn-primary btn-lg mt-3" href="#" role="button">Submit</button>
            </p>
        </form>
    </div>
</div>

{% endblock content %}

pages/templates/dashboardAdmin/RSCabang/daftarRSCabang.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='transaksi' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}

<div class="d-flex justify-content-center flex-column">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatRsCabang' %}">RS Cabang</a></li>
        <li class="breadcrumb-item active">Daftar RS</li>
    </ol>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Kode RS</th>
                <th scope="col">Nama</th>
                <th scope="col">Tanggal Pendirian</th>
                <th scope="col">Jalan</th>
                <th scope="col">Kota</th>
                <th scope="col">Nomor</th>
                {% if request.session.user.role == "admin" %}
                <th scope="col">Action</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for rs in rs_cabang %}
            <tr>
                <th scope="row">{{ rs.kode_rs }}</th>
                <td>{{ rs.nama }}</td>
                <td>{{ rs.tanggal_pendirian }}</td>
                <td>{{ rs.jalan }}</td>
                <td>{{ rs.kota }}</td>
                <td>{{ rs.nomor }}</td>
                {% if request.session.user.role == "admin" %}
                <td class="d-flex">
                    <a class="btn btn-primary" href="{% url 'pages:updateRsCabang' rs.kode_rs %}">Update</a>
                    <form action="{% url 'pages:deleteRsCabang' rs.kode_rs %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger" style="color: #fff;">Delete</button>
                    </form>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- update Modal -->
    <div class="modal fade" id="update-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Form Update RS Cabang</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="hide" id="success">
                        <div class="container d-flex justify-content-center align-items-center">
                            <lottie-player src="https://assets3.lottiefiles.com/packages/lf20_3w07tT.json"
                                background="transparent" speed="1" style="width: 200px; height: 200px;" loop autoplay>
                            </lottie-player>
                        </div>
                    </div>
                    <form id="modal-form" class="">
                        <div class="form-group">
                            <fieldset disabled="">
                                <label class="control-label" for="disabledInput">Kode RS</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="1.0"
                                    disabled="">
                            </fieldset>
                        </div>
                        <div class="form-group">
                            <label class="col-form-label" for="inputDefault">Nama</label>
                            <input type="text" class="form-control" value="RS Tangerang" placeholder="Default input"
                                id="inputDefault">
                        </div>
                        <div class="form-group">
                            <label class="col-form-label" for="inputDefault">Tanggal Pendirian</label>
                            <input type="text" class="form-control" value="1991-01-17" placeholder="Default input"
                                id="inputDefault">
                        </div>
                        <div class="form-group">
                            <label class="col-form-label" for="inputDefault">Jalan</label>
                            <input type="text" class="form-control" value="Jl. Lakeland Court"
                                placeholder="Default input" id="inputDefault">
                        </div>
                        <div class="form-group">
                            <label class="col-form-label" for="inputDefault">Kota</label>
                            <input type="text" class="form-control" value="Tangerang" placeholder="Default input"
                                id="inputDefault">
                        </div>
                        <div class="form-group">
                            <label class="col-form-label" for="inputDefault">Nomor</label>
                            <input type="text" class="form-control" value="10" placeholder="Default input"
                                id="inputDefault">
                        </div>
                    </form>
                </div>
                <div class="modal-footer d-flex justify-content-center align-items-center">
                    <button type="button" class="btn btn-primary" onclick="update()">Update</button>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}
{% block custom_scripts %}
<script>
    function update() {
        console.log("update Succes")
        $('#modal-form').toggleClass('hide');
        $('#success').toggleClass('hide');
        setTimeout(function () {
            $('#modal-form').toggleClass('hide');
            $('#success').toggleClass('hide');
        }, 3000);
    }
</script>
{% endblock custom_scripts %}

pages/templates/dashboardAdmin/RSCabang/listDokterRSCabang.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='RS' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}

<div class="d-flex justify-content-center flex-column">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatRsCabang' %}">RS Cabang</a></li>
        <li class="breadcrumb-item active">Daftar Dokter RS Cabang</li>
    </ol>
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Kode RS Cabang</th>
                <th scope="col">ID Dokter</th>
                {% if request.session.user.role == "admin" %}
                <th scope="col">Action</th>
                {% endif %}

            </tr>
        </thead>
        <tbody>
            {% for drs in dokter_rs_cabang %}
            <tr>
                
                    <td>{{ drs.kode_rs }}</td>
                    <td>{{ drs.id_dokter }}</td>
                    {% if request.session.user.role == "admin" %}

                    <td class="d-flex">
                        <a class="btn btn-primary" href="{% url 'pages:updateDokterRSCabang' drs.id_dokter drs.kode_rs %}">Update</a>
                            <form action ="{% url 'pages:deleteDokterRSCabang' drs.id_dokter drs.kode_rs %}" method = "POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger" style="color: #fff;">Delete</button>
                            </form>
                    </td>
                    {% endif %}

            </tr>
            {% endfor %}

        </tbody>
    </table>

    <!-- update Modal -->
    <div class="modal fade" id="update-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Form Update Dokter-RS Cabang</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="hide" id="success">
                        <div class="container d-flex justify-content-center align-items-center">
                            <lottie-player src="https://assets3.lottiefiles.com/packages/lf20_3w07tT.json"
                                background="transparent" speed="1" style="width: 200px; height: 200px;" loop autoplay>
                            </lottie-player>
                        </div>
                    </div>
                    <form id="modal-form" class="">
                        <div class="form-group">
                            <label for="exampleSelect1">ID Dokter</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>1.0</option>
                            </select>
                        <div class="form-group">
                            <label for="exampleSelect1">Kode RS Cabang</label>
                            <select class="form-control" id="exampleSelect1">
                                <option>1.0</option>
                            </select>
                        </div>
                    </form>
                </div>
                <div class="modal-footer d-flex justify-content-center align-items-center">
                    <button type="button" class="btn btn-primary" onclick="update()">Update</button>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}
{% block custom_scripts %}
<script>
    function update() {
        console.log("update Succes")
        $('#modal-form').toggleClass('hide');
        $('#success').toggleClass('hide');
        setTimeout(function () {
            $('#modal-form').toggleClass('hide');
            $('#success').toggleClass('hide');
        }, 3000);
    }
</script>
{% endblock custom_scripts %}

pages/templates/dashboardAdmin/RSCabang/updateDokterRSCabang.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='RS' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}
<div class="d-flex justify-content-center flex-column" style="width: 30vw;">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatRsCabang' %}">RS Cabang</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:listDokterRSCabang' %}">Daftar Dokter RS Cabang</a></li>
        <li class="breadcrumb-item active">Update Dokter RS Cabang</li>
    </ol>
    <div class="jumbotron" style="padding: 3rem 2rem;">
        <h2 class="">Update Dokter RS Cabang</h2>
        <form action="{% url 'pages:updateDokterRSCabang' id_dokter kode_rs %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputIdDokter">ID Dokter</label>
                <input type="text" class="form-control" id="inputIdDokter" name="id_dokter"
                       value="{{ id_dokter }}">
            </div>
            <div class="form-group">
                <label for="inputKodeRs">Kode RS</label>
                <input type="text" class="form-control" id="inputKodeRs" name="kode_rs"
                       value="{{ kode_rs }}">
            </div>
            <button class="btn btn-primary btn-lg mt-3" href="#" role="button">Submit</button>
        </form>
    </div>
</div>

{% endblock content %}

pages/templates/dashboardAdmin/RSCabang/updateRsCabang.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='RS' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}
<div class="d-flex justify-content-center flex-column" style="width: 30vw;">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatRsCabang' %}">RS Cabang</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:daftarRsCabang' %}">Daftar RS Cabang</a></li>
        <li class="breadcrumb-item active">Update RS</li>
    </ol>
    <div class="jumbotron" style="padding: 3rem 2rem;">
        <h2 class="">Update RS Cabang</h2>
        <form action="{% url 'pages:updateRsCabang' kode_rs %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputKodeRs">Kode RS Cabang</label>
                <input type="text" class="form-control" id="inputKodeRs" name="kode_rs" readonly value="{{ kode_rs }}">
            </div>
            <div class="form-group">
                <label for="inputNama">Nama</label>
                <input type="text" class="form-control" id="inputNama" name="nama" value="{{ nama }}">
            </div>
            <div class="form-group">
                <label for="inputTanggal">Tanggal Pendirian</label>
                <input type="date" class="form-control" id="inputTanggal" name="tanggal"
                    value="{{ tanggal_pendirian }}">
            </div>
            <div class="form-group">
                <label for="inputJalan">Jalan</label>
                <input type="text" class="form-control" id="inputJalan" name="jalan" value="{{ jalan }}">
            </div>
            <div class="form-group">
                <label for="inputNomor">Nomor</label>
                <input type="number" class="form-control" id="inputNomor" name="nomor" value="{{ nomor }}">
            </div>
            <div class="form-group">
                <label for="inputKota">Kota</label>
                <input type="text" class="form-control" id="inputKota" name="kota" value="{{ kota }}">
            </div>
            <button class="btn btn-primary btn-lg mt-3" href="#" role="button">Submit</button>
        </form>
    </div>
</div>

{% endblock content %}