medikago/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('user/', include('user.urls'))
]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path('', views.index, name="home"),
    path('dashboard/admin/', views.dashboardAdmin, name="dashAdmin"),
    path('dashboard/admin/profil', views.profil, name="profil"),
    ## konsultasi ##
    path('dashboard/admin/buatSesiKonsultasi',
         views.buatKonsultasi, name="buatKonsultasi"),
    path('dashboard/admin/daftarSesiKonsultasi',
         views.daftarKonsultasi, name="daftarKonsultasi"),
    path('dashboard/admin/updateSesiKonsultasi/<str:id_konsultasi>/',
         views.updateKonsultasi, name="updateKonsultasi"),
    path('dashboard/admin/deleteSesiKonsultasi/<str:id_konsultasi>',
         views.deleteKonsultasi, name="deleteKonsultasi"),
    ## poliklinik ##
    path('dashboard/admin/buatLayananJadwalPoliklinik',
         views.buatLayananJadwalPoliklinik, name="buatLayananJadwalPoliklinik"),
    path('dashboard/admin/daftarLayananJadwalPoliklinik',
         views.daftarLayananJadwalPoliklinik, name="daftarLayananJadwalPoliklinik"),
    path('dashboard/admin/updateLayananJadwalPoliklinik/<str:id_poliklinik>',
         views.updateLayananJadwalPoliklinik, name="updateLayananJadwalPoliklinik"),
    path('dashboard/admin/deleteLayananJadwalPoliklinik/<str:id_poliklinik>',
         views.deleteLayananJadwalPoliklinik, name="deleteLayananJadwalPoliklinik"),
    ## rs ##
    path('dashboard/admin/buatRsCabang',
         views.buatRsCabang, name="buatRsCabang"),
    path('dashboard/admin/daftarRsCabang',
         views.daftarRsCabang, name="daftarRsCabang"),
    path('dashboard/admin/updateRsCabang/<str:kode_rs>',
         views.updateRsCabang, name="updateRsCabang"),
    path('dashboard/admin/deleteRsCabang/<str:kode_rs>',
         views.deleteRsCabang, name="deleteRsCabang"),
    path('dashboard/admin/daftarDokterRSCabang',
         views.daftarDokterRsCabang, name="daftarDokterRSCabang"),
    path('dashboard/admin/listDokterRSCabang',
         views.listDokterRsCabang, name="listDokterRSCabang"),
    path('dashboard/admin/updateDokterRSCabang/<str:id_dokter>/<str:kode_rs>',
         views.updateDokterRsCabang, name="updateDokterRSCabang"),
    path('dashboard/admin/deleteDokterRSCabang/<str:id_dokter>/<str:kode_rs>',
         views.deleteDokterRsCabang, name="deleteDokterRSCabang"),

    ## tindakan ##
    path('dashboard/admin/buatTindakan',
         views.buatTindakan, name='buatTindakan'),
    path('dashboard/admin/daftarTindakan',
         views.daftarTindakan, name='daftarTindakan'),
    path('dashboard/admin/updateTindakan/<str:no_urut>/<str:id_konsultasi>',
         views.updateTindakan, name="updateTindakan"),
    path('dashboard/admin/deleteTindakan/<str:no_urut>/<str:id_konsultasi>',
         views.deleteTindakan, name="deleteTindakan"),
    path('dashboard/admin/buatTindakanPoliklinik',
         views.buatTindakanPoliklinik, name='buatTindakanPoliklinik'),
    path('dashboard/admin/daftarTindakanPoliklinik',
         views.daftarTindakanPoliklinik, name='daftarTindakanPoliklinik'),
    path('dashboard/admin/updateTindakanPoliklinik/<str:id_tindakan_poli>',
         views.updateTindakanPoliklinik, name="updateTindakanPoliklinik"),
    path('dashboard/admin/deleteTindakanPoliklinik/<str:id_tindakan_poli>',
         views.deleteTindakanPoliklinik, name="deleteTindakanPoliklinik"),
    ## transaksi ##
    path('dashboard/admin/buatTransaksi',
         views.buatTransaksi, name="buatTransaksi"),
    path('dashboard/admin/daftarTransaksi',
         views.daftarTransaksi, name="daftarTransaksi"),
    path('dashboard/admin/updateTransaksi/<str:id_transaksi>',
         views.updateTransaksi, name="updateTransaksi"),
    path('dashboard/admin/deleteTransaksi/<str:id_transaksi>',
         views.deleteTransaksi, name="deleteTransaksi"),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('roles/', views.roles, name="roles"),
    path('registerAdmin/', views.registerAdmin, name="registerAdmin"),
    path('registerDokter/', views.registerDokter, name="registerDokter"),
    path('registerPasien/', views.registerPasien, name="registerPasien"),
]

pages/templates/dashboardAdmin/components/navbar.html
<nav id="sidebar">
    <div class="sidebar-header">
        <h3>MEDIKAGO</h3>
    </div>


    <ul class="list-unstyled components">

        {% if request.session.user.role == "admin" %}
        <p>ADMIN DASHBOARD</p>
        {% else %}
        <p>USER DASHBOARD</p>
        {% endif %}

        <li class="{% if current_nav == 'profil' %} active {% endif %}"><a href="{% url 'pages:profil' %}">Profil</a>
        </li>

        <li class="{% if current_nav == 'konsultasi' %} active {% endif %}"><a href="#konsultasiSubmenu"
                data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Sesi Konsultasi</a>
            <ul class="collapse list-unstyled" id="konsultasiSubmenu">
                {% if request.session.user.role == "admin" %}
                <li><a href="{% url 'pages:buatKonsultasi' %}">Buat Sesi Konsultasi</a></li>
                {% endif %}
                <li><a href="{% url 'pages:daftarKonsultasi' %}">Daftar Sesi Konsultasi</a></li>
            </ul>
        </li>
        <li class="{% if current_nav == 'poliklinik' %} active {% endif %}"><a href="#layananSubmenu"
                data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Poliklinik</a>
            <ul class="collapse list-unstyled" id="layananSubmenu">
                <li><a href="{% url 'pages:buatLayananJadwalPoliklinik' %}">Buat Layanan dan Jadwal Poliklinik</a></li>
                {% if request.session.user.role == "admin" %}
                <li><a href="{% url 'pages:daftarLayananJadwalPoliklinik' %}">Daftar Layanan dan Jadwal Poliklinik</a>
                </li>
                {% endif %}
            </ul>
        </li>
        <li class="{% if current_nav == 'RS' %} active {% endif %}"><a href="#RSSubmenu" data-toggle="collapse"
                aria-expanded="false" class="dropdown-toggle">RS
                Cabang</a>
            <ul class="collapse list-unstyled" id="RSSubmenu">
                {% if request.session.user.role == "admin" %}
                <li><a href="{% url 'pages:buatRsCabang' %}">Buat RS Cabang</a></li>
                {% endif %}
                <li><a href="{% url 'pages:daftarRsCabang' %}">Daftar RS Cabang</a></li>
                <li><a href="{% url 'pages:listDokterRSCabang' %}">List Dokter RS Cabang</a></li>
                {% if request.session.user.role == "admin" %}
                <li><a href="{% url 'pages:daftarDokterRSCabang' %}">Daftarkan Dokter RS Cabang</a></li>
                <li><a class="list-group-item-action disabled" style="color: #888888;">Daftarkan Administrator</a></li>
                {% endif %}
            </ul>
        </li>
        <li class="{% if current_nav == 'tindakan' %} active {% endif %}"><a href="#tindakanSubmenu"
                data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Tindakan</a>
            <ul class="collapse list-unstyled" id="tindakanSubmenu">
                {% if request.session.user.role == "admin" %}
                <li><a href="{% url 'pages:buatTindakan' %}">Buat Tindakan</a></li>
                {% endif %}
                <li><a href="{% url 'pages:daftarTindakan' %}">Daftar Tindakan</a></li>
                {% if request.session.user.role == "admin" %}
                <li><a href="{% url 'pages:buatTindakanPoliklinik' %}">Buat Tindakan Poliklinik</a></li>
                {% endif %}
                <li><a href="{% url 'pages:daftarTindakanPoliklinik' %}">Daftar Tindakan Poliklinik</a></li>
            </ul>
        </li>
        <li class="{% if current_nav == 'resep' %} active {% endif %}"><a href="#resepSubmenu" data-toggle="collapse"
                aria-expanded="false" class="dropdown-toggle">Resep
                dan Obat</a>
            <ul class="collapse list-unstyled" id="resepSubmenu">
                {% if request.session.user.role == "admin" %}
                <li><a class="list-group-item-action disabled" style="color: #888888;">Buat Resep</a></li>
                {% endif %}
                <li><a class="list-group-item-action disabled" style="color: #888888;">Daftar Resep</a></li>
                {% if request.session.user.role == "admin" %}
                <li><a class="list-group-item-action disabled" style="color: #888888;">Buat Obat</a></li>
                {% endif %}
                <li><a class="list-group-item-action disabled" style="color: #888888;">Daftar Obat</a></li>
            </ul>
        </li>
        <li class="{% if current_nav == 'transaksi' %} active {% endif %}"><a href="#transaksiSubmenu"
                data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Transaksi</a>
            <ul class="collapse list-unstyled" id="transaksiSubmenu">
                {% if request.session.user.role == "admin" %}
                <li><a href="{% url 'pages:buatTransaksi' %}">Buat Transaksi</a></li>
                {% endif %}
                <li><a href="{% url 'pages:daftarTransaksi' %}">Daftar Transaksi</a></li>
            </ul>
        </li>
        <ul class="list-unstyled CTAs">
            <li><a class="download" href="{% url 'user:logout' %}">Logout</a></li>
        </ul>
    </ul>
</nav>