medikago/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('user/', include('user.urls'))
]

pages/urls.py
from django.urls import path
from . import views

app_name = "pages"

urlpatterns = [
    path('', views.index, name="home"),
    path('dashboard/admin/', views.dashboardAdmin, name="dashAdmin"),
    path('dashboard/admin/profil', views.profil, name="profil"),
    ## konsultasi ##
    path('dashboard/admin/buatSesiKonsultasi',
         views.buatKonsultasi, name="buatKonsultasi"),
    path('dashboard/admin/daftarSesiKonsultasi',
         views.daftarKonsultasi, name="daftarKonsultasi"),
    path('dashboard/admin/updateSesiKonsultasi/<str:id_konsultasi>/',
         views.updateKonsultasi, name="updateKonsultasi"),
    path('dashboard/admin/deleteSesiKonsultasi/<str:id_konsultasi>',
         views.deleteKonsultasi, name="deleteKonsultasi"),
    ## poliklinik ##
    path('dashboard/admin/buatLayananJadwalPoliklinik',
         views.buatLayananJadwalPoliklinik, name="buatLayananJadwalPoliklinik"),
    path('dashboard/admin/daftarLayananJadwalPoliklinik',
         views.daftarLayananJadwalPoliklinik, name="daftarLayananJadwalPoliklinik"),
    path('dashboard/admin/updateLayananJadwalPoliklinik/<str:id_poliklinik>',
         views.updateLayananJadwalPoliklinik, name="updateLayananJadwalPoliklinik"),
    path('dashboard/admin/deleteLayananJadwalPoliklinik/<str:id_poliklinik>',
         views.deleteLayananJadwalPoliklinik, name="deleteLayananJadwalPoliklinik"),
    ## rs ##
    path('dashboard/admin/buatRsCabang',
         views.buatRsCabang, name="buatRsCabang"),
    path('dashboard/admin/daftarRsCabang',
         views.daftarRsCabang, name="daftarRsCabang"),
    path('dashboard/admin/updateRsCabang/<str:kode_rs>',
         views.updateRsCabang, name="updateRsCabang"),
    path('dashboard/admin/deleteRsCabang/<str:kode_rs>',
         views.deleteRsCabang, name="deleteRsCabang"),
    path('dashboard/admin/daftarDokterRSCabang',
         views.daftarDokterRsCabang, name="daftarDokterRSCabang"),
    path('dashboard/admin/listDokterRSCabang',
         views.listDokterRsCabang, name="listDokterRSCabang"),
    path('dashboard/admin/updateDokterRSCabang/<str:id_dokter>/<str:kode_rs>',
         views.updateDokterRsCabang, name="updateDokterRSCabang"),
    path('dashboard/admin/deleteDokterRSCabang/<str:id_dokter>/<str:kode_rs>',
         views.deleteDokterRsCabang, name="deleteDokterRSCabang"),

    ## tindakan ##
    path('dashboard/admin/buatTindakan',
         views.buatTindakan, name='buatTindakan'),
    path('dashboard/admin/daftarTindakan',
         views.daftarTindakan, name='daftarTindakan'),
    path('dashboard/admin/updateTindakan/<str:no_urut>/<str:id_konsultasi>',
         views.updateTindakan, name="updateTindakan"),
    path('dashboard/admin/deleteTindakan/<str:no_urut>/<str:id_konsultasi>',
         views.deleteTindakan, name="deleteTindakan"),
    path('dashboard/admin/buatTindakanPoliklinik',
         views.buatTindakanPoliklinik, name='buatTindakanPoliklinik'),
    path('dashboard/admin/daftarTindakanPoliklinik',
         views.daftarTindakanPoliklinik, name='daftarTindakanPoliklinik'),
    path('dashboard/admin/updateTindakanPoliklinik/<str:id_tindakan_poli>',
         views.updateTindakanPoliklinik, name="updateTindakanPoliklinik"),
    path('dashboard/admin/deleteTindakanPoliklinik/<str:id_tindakan_poli>',
         views.deleteTindakanPoliklinik, name="deleteTindakanPoliklinik"),
    ## transaksi ##
    path('dashboard/admin/buatTransaksi',
         views.buatTransaksi, name="buatTransaksi"),
    path('dashboard/admin/daftarTransaksi',
         views.daftarTransaksi, name="daftarTransaksi"),
    path('dashboard/admin/updateTransaksi/<str:id_transaksi>',
         views.updateTransaksi, name="updateTransaksi"),
    path('dashboard/admin/deleteTransaksi/<str:id_transaksi>',
         views.deleteTransaksi, name="deleteTransaksi"),
]

user/urls.py
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('roles/', views.roles, name="roles"),
    path('registerAdmin/', views.registerAdmin, name="registerAdmin"),
    path('registerDokter/', views.registerDokter, name="registerDokter"),
    path('registerPasien/', views.registerPasien, name="registerPasien"),
]

pages/templates/dashboardAdmin/Transaksi/buatTransaksi.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='transaksi' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}
<div class="d-flex justify-content-center flex-column" style="width: 30vw;">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatTransaksi' %}">Transaksi</a></li>
        <li class="breadcrumb-item active">Buat Transaksi</li>
    </ol>
    <div class="jumbotron" style="padding: 3rem 2rem;">
        <h2 class="">Form Pembuatan Transaksi</h2>
        <form action="{% url 'pages:buatTransaksi' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleSelect1">Nomor Rekam Medis Pasien</label>
                <select class="form-control" id="exampleSelect1" name="no_rekam_medis" required>
                    {% for ps in no_rekam_medis %}
                    <option>{{ ps.no_rekam_medis }}</option>
                    {% endfor %}
                </select>
            </div>
            <button class="btn btn-primary btn-lg mt-3" href="#" role="button" type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock content %}

pages/templates/dashboardAdmin/Transaksi/daftarTransaksi.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='transaksi' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}

<div class="d-flex justify-content-center flex-column">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatTransaksi' %}">Daftar Transaksi</a></li>
        <li class="breadcrumb-item active">Daftar Transaksi</li>
    </ol>
    <table class="table table-hover" style="text-align: center;">
        <thead>
            <tr>
                <th scope="col">Nomor</th>
                <th scope="col">Tanggal</th>
                <th scope="col">Status</th>
                <th scope="col">Total Biaya</th>
                <th scope="col">Waktu Pembayaran</th>
                <th scope="col">Nomor Rekam Medis Pasien</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for tr in transaksi %}
            <tr>
                <th scope="row">{{ tr.id_transaksi }}</th>
                <td>{{ tr.tanggal }}</td>
                <td>{{ tr.status }}</td>
                <td>{{ tr.total_biaya }}</td>
                <td>{{ tr.waktu_pembayaran }}</td>
                <td>{{ tr.no_rekam_medis }}</td>
                <td class="d-flex">
                    <a class="btn btn-primary " data-toggle="modal" href="#update-modal">Update</a>
                    <form action="{% url 'pages:deleteTransaksi' tr.id_transaksi %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger" style="color: #fff;">Delete</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <!-- update Modal -->
    <div class="modal fade" id="update-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Form Update Transaksi</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="hide" id="success">
                        <div class="container d-flex justify-content-center align-items-center">
                            <lottie-player src="https://assets3.lottiefiles.com/packages/lf20_3w07tT.json"
                                background="transparent" speed="1" style="width: 200px; height: 200px;" loop autoplay>
                            </lottie-player>
                        </div>
                    </div>
                    <form id="modal-form" class="">
                        <div class="form-group">
                            <fieldset disabled="">
                                <label class="control-label" for="disabledInput">ID Transaksi</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="1" disabled="">
                            </fieldset>
                        </div>
                        <div class="form-group">
                            <label class="col-form-label" for="inputDefault">Tanggal</label>
                            <input type="text" class="form-control" value="2 Juli 2020" placeholder="Default input"
                                id="inputDefault">
                        </div>
                        <div class="form-group">
                            <label class="col-form-label" for="inputDefault">Status</label>
                            <input type="text" class="form-control" value="Sudah Dibayar" placeholder="Default input"
                                id="inputDefault">
                        </div>
                        <div class="form-group">
                            <fieldset disabled="">
                                <label class="control-label" for="disabledInput">Total Biaya</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="Rp250000"
                                    disabled="">
                            </fieldset>
                        </div>
                        <div class="form-group">
                            <label class="col-form-label" for="inputDefault">Waktu Pembayaran</label>
                            <input type="text" class="form-control" value="3 Juli 2020, 17:10:39" placeholder="Default input"
                                id="inputDefault">
                        </div>
                        <div class="form-group">
                            <fieldset disabled="">
                                <label class="control-label" for="disabledInput">Nomor Rekam Medis Pasien</label>
                                <input class="form-control" id="disabledInput" type="text" placeholder="1" disabled="">
                            </fieldset>
                        </div>
                    </form>
                </div>
                <div class="modal-footer d-flex justify-content-center align-items-center">
                    <button type="button" class="btn btn-primary" onclick="update()">Update</button>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}
{% block custom_scripts %}
<script>
    function update() {
        console.log("update Succes")
        $('#modal-form').toggleClass('hide');
        $('#success').toggleClass('hide');
        setTimeout(function () {
            $('#modal-form').toggleClass('hide');
            $('#success').toggleClass('hide');
        }, 3000);
    }
</script>
{% endblock custom_scripts %}

pages/templates/dashboardAdmin/Transaksi/updateTransaksi.html
{% extends 'dashboardAdmin/dashboard.html' %}

{% block navbar %}
{% with current_nav='transaksi' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block content %}
<div class="d-flex justify-content-center flex-column" style="width: 30vw;">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'pages:dashAdmin' %}">Dashboard</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:buatRsCabang' %}">Transaksi</a></li>
        <li class="breadcrumb-item"><a href="{% url 'pages:daftarRsCabang' %}">Daftar Transaksi</a></li>
        <li class="breadcrumb-item active">Update Transaksi</li>
    </ol>
    <div class="jumbotron" style="padding: 3rem 2rem;">
        <h2 class="">Update Transaksi</h2>
        <form action="{% url 'pages:updateRsCabang' kode_rs %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="inputKodeRs">ID Transaksi</label>
                <input type="text" class="form-control" id="inputIDTransaksi" name="id_transaksi" readonly value="{{ id_transaksi }}">
            </div>
            <div class="form-group">
                <label for="inputTanggal">Tanggal</label>
                <input type="date" class="form-control" id="inputTanggal" name="tanggal"
                    value="{{ tanggal }}">
            </div>
            <div class="form-group">
                <label for="inputJalan">Status</label>
                <input type="text" class="form-control" id="inputStatus" name="status" value="{{ status }}">
            </div>
            <div class="form-group">
                <label for="inputNomor">Total Biaya</label>
                <input type="number" class="form-control" id="inputTotalBiara" name="total_biaya" readonly value="{{ total_biaya }}">
            </div>
            <div class="form-group">
                <label for="inputKota">Waktu Pembayaran</label>
                <input type="text" class="form-control" id="inputWaktuPembayaran" name="waktu_pembayaran" value="{{ waktu_pembayaran }}">
            </div>
            <div class="form-group">
                <label for="inputKota">Nomor Rekam Medis</label>
                <input type="text" class="form-control" id="inputNoRekamMedis" name="no_rekam_medis" readonly value="{{ no_rekam_medis }}">
            </div>
            <button class="btn btn-primary btn-lg mt-3" href="#" role="button">Submit</button>
        </form>
    </div>
</div>

{% endblock content %}